name: fitness_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^5.0.0
  url_launcher: ^6.0.17
  rflutter_alert: ^2.0.4
  modal_progress_hud_nsn: ^0.5.1
  shimmer: ^3.0.0
  video_player: ^2.2.18
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  app_settings: ^6.1.1
  http: ^1.3.0
  week_of_year: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  audioplayers: ^6.4.0
  grouped_list: ^6.0.0
  intl: ^0.20.2
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/beeps/
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
    - family: OpenSans-Light
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSans-Medium
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf
    - family: OpenSans-SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: OpenSans-ExtraBold
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf




